# Name of workflow
name: Pull Request Workflow - Composite Action

# Workflow trigger event. We want the workflow to trigger on a pull
# request to main
on:
  pull_request:
    branches: 
      - main
  
jobs:

  # Build and test the PR
  build-test-branch:

    name: "Build Test Of PR using Composite Action"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Jobs check pull request
        run: echo "from jobs check pull reuqest"